### ISSUE TITLE
Installation fails on Raspberry Pi 4 server

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/pleroma_ynh#150]
**Describe the bug**
Attempting to install Pleroma on my Raspberry Pi 4 server results in an error message related to a database connection error.

**Versions**
- Hardware: *Raspberry Pi 4 at home*
- YunoHost version: 4.0.8.3
- I have access to my server: *Through SSH / webadmin / direct access*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *no*
- Using, or trying to install package version/branch: *stable*

**To Reproduce**
*Steps to reproduce the behavior.*
    ```
    sudo yunohost app install pleroma
    ```

**Expected behavior**
The application should be installed and available after the installer is done.

**Logs**

https://paste.yunohost.org/raw/mayaropoju

```sh
Warning: ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2959ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
Warning:
Warning:   1. By tracking down slow queries and making sure they are running fast enough
Warning:   2. Increasing the pool_size (albeit it increases resource consumption)
Warning:   3. Allow requests to wait longer by increasing :queue_target and :queue_interval
Warning:
Warning: See DBConnection.start_link/2 for more information
Warning:
Warning:     (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
Warning:     (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
Warning:     (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:686: Ecto.Adapters.SQL.execute_ddl/4
Warning:     (ecto_sql 3.4.5) lib/ecto/migrator.ex:641: Ecto.Migrator.verbose_schema_migration/3
Warning:     (ecto_sql 3.4.5) lib/ecto/migrator.ex:484: Ecto.Migrator.lock_for_migrations/4
Warning:     (ecto_sql 3.4.5) lib/ecto/migrator.ex:406: Ecto.Migrator.run/4
Warning:     (ecto_sql 3.4.5) lib/ecto/migrator.ex:142: Ecto.Migrator.with_repo/3
Warning:     (pleroma 2.1.2) lib/mix/tasks/pleroma/ecto/migrate.ex:63: Mix.Tasks.Pleroma.Ecto.Migrate.run/1
Error: Could not install pleroma: An error occurred inside the app installation script
Info: The operation 'Install the 'pleroma' app' could not be completed. Please share the full log of this operation using the command 'yunohost log display 20201229-070439-app_install-pleroma --share' to get help
Warning: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG -
Info: WARNING -     (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
Info: DEBUG - To fix the first issue, run "mix ecto.create".
Info: WARNING -     (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
Info: DEBUG -
Info: WARNING -     (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:686: Ecto.Adapters.SQL.execute_ddl/4
Info: DEBUG - To address the second, you can run "mix ecto.drop" followed by
Info: WARNING -     (ecto_sql 3.4.5) lib/ecto/migrator.ex:641: Ecto.Migrator.verbose_schema_migration/3
Info: DEBUG - "mix ecto.create". Alternatively you may configure Ecto to use
Info: WARNING -     (ecto_sql 3.4.5) lib/ecto/migrator.ex:484: Ecto.Migrator.lock_for_migrations/4
Info: DEBUG - another table for managing migrations:
Info: WARNING -     (ecto_sql 3.4.5) lib/ecto/migrator.ex:406: Ecto.Migrator.run/4
Info: DEBUG -
Info: WARNING -     (ecto_sql 3.4.5) lib/ecto/migrator.ex:142: Ecto.Migrator.with_repo/3
Info: DEBUG -     config :pleroma, Pleroma.Repo,
Info: WARNING -     (pleroma 2.1.2) lib/mix/tasks/pleroma/ecto/migrate.ex:63: Mix.Tasks.Pleroma.Ecto.Migrate.run/1
Info: DEBUG -       migration_source: "some_other_table_for_schema_migrations"
Info: DEBUG -
Info: DEBUG - The full error report is shown below.
Info: DEBUG -
Info: DEBUG - + ynh_exit_properly
```

**Comment by yalh76** [comment]
The issue you have is that you already have a postgresl database named pleroma .... You should install pgadmin_ynh for example and manually remove that database...
