### ISSUE TITLE
installation failed - /home/yunohost.app/pleroma already existed

### ISSUE THREAD

**Issue by chri2** [YunoHost-Apps/pleroma_ynh#270]
When trying to install Pleroma it failed with `DEBUG - !!! Config path is not declared! Please ensure it exists and that PLEROMA_CONFIG_PATH is unset or points to an existing file`.

```
root@link-goe:~# ls -ld /home/yunohost.app/pleroma
drwxr-x--- 4 988 988 4096  8. Sep 2022  /home/yunohost.app/pleroma
```

I didn't remember I already had the app installed sometimes. My old 20220915-112001-app_remove-pleroma.log is empty for some reason.

Maybe this is already fixed when removing a more recent version.

**Comment by chri2** [comment]
```
98166 INFO DEBUG - + sudo -u pleroma -i /var/www/pleroma/live/bin/pleroma_ctl instance gen --force --output /etc/pleroma/config.exs --output-psql /tmp/setup_db.psql --domain dorfbrunnen.ween.de --instance-name 'Dorfbrunnen Weende' --admin-email admin_chris@link-goe.de --notify-email admin_chris@link-goe.de --dbhost localhost --dbname pleroma --dbuser pleroma --dbpass ********** --rum N --indexable Y --db-configurable Y --uploads-dir /home/yunohost.app/pleroma/uploads --static-dir /home/yunohost.app/pleroma/static --listen-ip 127.0.0.1 --listen-port 8097 --strip-uploads-location Y --read-uploads-description Y --anonymize-uploads Y --dedupe-uploads Y
98168 INFO DEBUG - !!! Config path is not declared! Please ensure it exists and that PLEROMA_CONFIG_PATH is unset or points to an existing file
98169 INFO DEBUG - ** (MatchError) no match of right hand side value: {[force: true, output: "/etc/pleroma/config.exs", output_psql: "/tmp/setup_db.psql", domain: "dorfbrunnen.ween.de", instance_name: "Dorfbrunnen", admin_email: "admin_chris@link-goe.de", notify_email: "admin_chris@link-goe.de", dbhost: "localhost", dbname: "pleroma", dbuser: "pleroma", dbpass: "**********", rum: "N", indexable: "Y", db_configurable: "Y", uploads_dir: "/home/yunohost.app/pleroma/uploads", static_dir: "/home/yunohost.app/pleroma/static", listen_ip: "127.0.0.1", listen_port: "8097", strip_uploads_location: "Y", read_uploads_description: "Y", anonymize_uploads: "Y", dedupe_uploads: "Y"], ["Weende"], []}
98171 INFO DEBUG -     (pleroma 2.6.2) lib/mix/tasks/pleroma/instance.ex:15: Mix.Tasks.Pleroma.Instance.run/1
98173 INFO DEBUG -     (stdlib 3.14.2.3) erl_eval.erl:680: :erl_eval.do_apply/6
98176 INFO DEBUG -     (elixir 1.11.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
```

**Comment by chri2** [comment]
Either my `--label "two words"` or `--args "…name= two words…` broke the installation.

Replacing the string "two words" with "two_words" made the install work.

**Comment by artlog** [comment]
@chri2 reviewing open bugs.
Yes i confirm install fails if instance name contains spaces.

**Comment by artlog** [comment]
This limitation was already seen in #144 but not recorded as such.

**Comment by artlog** [comment]
This is a regression, it was fixed in #144 but was lost e288f029a9fe42b4a02a46cb3c92b1307229a6b1 (2024-01-12) when upgrading to Manifest v2.
Still #144 fixe was to replace spaces with '_' , it seems that real fix should be to find out where in fail in pleroma_ctl argument passing, this is an upstream weakness.

**Comment by artlog** [comment]
clearly this one is related of upstream pleroma_ctl argument passing using `FULL_ARGS="$*"`

**Comment by artlog** [comment]
related upstream ticket : https://git.pleroma.social/pleroma/pleroma/issues/7874

**Comment by artlog** [comment]
It is possible to change instance name afterwards in pleroma-FE web administration, so this limitation is only during install.

**Comment by artlog** [comment]
new version 2.10.2 ( #308  ) was tested successfully with spaces in instance name

**Comment by artlog** [comment]
2.10.2 is released, this is fixed,
